name: Attach Artifact to Release

on:
  pull_request:
    types:
      - closed

jobs:

  release-prepare:
    uses: liquibase/build-logic/.github/workflows/extension-release-prepare.yml@v0.3.2
    secrets: inherit

  attach-artifact-to-release:
    uses: liquibase/build-logic/.github/workflows/extension-attach-artifact-release.yml@v0.3.2
    secrets: inherit
