name: Build & Test

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  push:
    branches:
      - main

jobs:
  unit-test:
    name: Unit Tests - Java ${{ matrix.java }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [8, 11, 16]

    steps:
    - uses: actions/checkout@v2
    - name: Cache Local Maven Repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java }}
        distribution: 'temurin'
        cache: 'maven'

    - name: Unit Tests - Java ${{ matrix.java }}
      run: mvn -B surefire:test --file pom.xml

  integration-tests:
    name: Integration Test - Java ${{ matrix.java }}
    runs-on: ubuntu-latest
    needs: unit-test
    strategy:
      matrix:
        java: [8, 11, 17]
        mongodb: [4]
    services:
      mongodb:
        image: mongo:${{ matrix.mongodb }}
        ports:
          - 27017-27019:27017-27019

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: 'maven'
      - name: Integration Test - Java ${{ matrix.java }}
        run: mvn -B clean test verify -Prun-its --file pom.xml

  harness-tests:
    name: Harness Tests - Java ${{ matrix.java }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 11, 17 ]
        mongodb: [ 4 ]
    services:
      mongodb:
        image: mongo:${{ matrix.mongodb }}
        env:
          MONGO_INITDB_DATABASE: lbcat
        ports:
          - 27020:27017

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: 'maven'

      - name: Build Cache
        uses: actions/cache@v3.0.5
        with:
          key: build-${{ github.run_number }}-${{ github.run_attempt }}
          path: |
            **/target/**
            ~/.m2/repository/org/liquibase/


      - name: Harness Foundational Test Suite Run - Java ${{ matrix.java }}
        run: mvn -Dtest="HarnessNoSqlCompatibility" -DdbName=mongodb -DdbUrl=mongodb://localhost:27020/lbcat clean package

      - name: Archive Mongo Database Test Results
        uses: actions/upload-artifact@v3
        with:
          name: mongodb-test-results
          path: build/spock-reports
