name: Release Extension to Sonatype

on:
  release:
    types: [published]

jobs:
    release:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2

        - name: Set up Java for publishing to Maven Central Repository
          uses: actions/setup-java@v2
          with:
            java-version: '11'
            distribution: 'adopt'
            server-id: sonatype-nexus-staging
            server-username: MAVEN_USERNAME
            server-password: MAVEN_PASSWORD
            gpg-private-key: ${{ secrets.GPG_SECRET }}
            gpg-passphrase: GPG_PASSPHRASE

        - name: Download artifact
          id: download-artifact
          uses: dawidd6/action-download-artifact@v2
          with:
            github_token: ${{secrets.BOT_TOKEN}}
            workflow: create-release.yml
            name: liquibase-mongodb
            check_artifacts: true
            skip_unpack: false
            if_no_artifact_found: fail
            workflow_conclusion: ""

        - name: Publish to the Maven Central Repository
          run: mvn clean deploy:deploy-file -Dfile=${{ github.event.release.tag_name}}.jar -Dmaven.test.skip -DgeneratePom=false -DrepositoryId=sonatype-nexus-staging -Durl=file:../local_repo/snapshot -P release
          env:
            MAVEN_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
            MAVEN_PASSWORD: ${{ secrets.SONATYPE_TOKEN }}
            GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

