name: Release Drafter

on:
  workflow_dispatch:
  push:
    branches:
      - main
    
permissions:
  contents: read

jobs:
  update_release_draft:
    permissions:
        # write permission is required to create a github release
        contents: write
        # write permission is required for autolabeler
        # otherwise, read permission is required at least
        pull-requests: write
    runs-on: ubuntu-latest
    steps:
      # Drafts your next Release notes as Pull Requests are merged into the default branch
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v2
      - run: git fetch --prune --unshallow
      
      #  Get the $PREVIOUS_TAG for release-drafter job in .github/release-drafter.yml
      - name: Get previous tag
        id: prev_tag
        run: |
          PREVIOUS_TAG=$(git describe --tags --abbrev=0 HEAD^)
          echo "::set-output name=previous_tag::$PREVIOUS_TAG"

      - name: Run Release Drafter
        uses: release-drafter/release-drafter@v5
        with:
          config-path: .github/release-drafter.yml
          name-template: "v${{ steps.prev_tag.outputs.previous_tag }}"    
    