name: Build and Test

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    paths-ignore:
      - 'documentation.Dockerfile'
      - 'documentation.dockerignore'
      - 'mkdocs.yml'
      - 'docs/**'

jobs:
  build-test:
    uses: liquibase/build-logic/.github/workflows/os-extension-test.yml@v0.3.2
    secrets: inherit

  integration-test:
    name: Java ${{ matrix.java }}
    runs-on: ubuntu-latest
    needs: build-test
    strategy:
      matrix:
        java: [8, 11, 17]
        mongodb: [4]
    services:
      mongodb:
        image: mongo:${{ matrix.mongodb }}
        ports:
          - 27017-27019:27017-27019

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: 'maven'

      - name: Run Tests With Maven
        run: mvn --quiet --show-version --batch-mode verify
        env:
          NEO4J_VERSION: ${{ matrix.neo4j_version }}
          ENTERPRISE: ${{ matrix.enterprise }}